/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import javax.swing.JOptionPane;
import backend.LibrarianUser;
import backend.AdminRole;
import javax.swing.JFrame;

/**
 *
 * @author yasmi
 */
public class AdminRoleWindow extends javax.swing.JFrame implements Node{
    private Node parent;
    private AddLibrarian al;
    private View vl;
    private RemoveLibrarian rl;
    public static AdminRole adminRole;
  
    /**
     * Creates new form AdminRole
     */
    public AdminRoleWindow() {
        initComponents();
        al = new AddLibrarian();
        vl = null;
        rl = new RemoveLibrarian();
        adminRole = new AdminRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLibrarian = new javax.swing.JButton();
        viewLibrarians = new javax.swing.JButton();
        RemoveLibrarian = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Role");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        addLibrarian.setBackground(new java.awt.Color(0, 0, 0));
        addLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        addLibrarian.setText("Add Librarian");
        addLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibrarianActionPerformed(evt);
            }
        });

        viewLibrarians.setBackground(new java.awt.Color(0, 0, 0));
        viewLibrarians.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewLibrarians.setForeground(new java.awt.Color(255, 255, 255));
        viewLibrarians.setText("View Librarians");
        viewLibrarians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLibrariansActionPerformed(evt);
            }
        });

        RemoveLibrarian.setBackground(new java.awt.Color(0, 0, 0));
        RemoveLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RemoveLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        RemoveLibrarian.setText("Remove Librarian");
        RemoveLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLibrarianActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLibrarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewLibrarians, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveLibrarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(addLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewLibrarians, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoveLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLibrarianActionPerformed
        // TODO add your handling code here:]
       this.setVisible(false);
       al.setParentNode(this);
       al.setVisible(true);
      
    }//GEN-LAST:event_addLibrarianActionPerformed

    private void viewLibrariansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLibrariansActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
         
         if (vl == null){
            vl = new View(new String[]{"Librarian Id","Name","Email",
                "Address","Phone Number"});
        }
         
         LibrarianUser[ ]users = adminRole.getListOfLibrarians();
         String [][] librarianData  = 
                 new String[users.length][5];
         String str;
         for (int i = 0; i< users.length; i++ ){
           str = users[i].lineRepresentation();
           librarianData[i] = str.split(",");
         } 
        
         vl.setData(librarianData);
         vl.setTitle("View librarians");
         vl.setParentNode(this);
         vl.setVisible(true);
    }//GEN-LAST:event_viewLibrariansActionPerformed

    private void RemoveLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveLibrarianActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         rl.setParentNode(this);
         rl.setVisible(true);
    }//GEN-LAST:event_RemoveLibrarianActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        adminRole.logout();
        ((JFrame)(getParentNode().getParentNode())).setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        // Check this method???????
        JOptionPane.showMessageDialog(null,
                "if you want to exist this window Logout");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRoleWindow().setVisible(true);
            }
        });
    }
    
    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
       this.parent = node;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton RemoveLibrarian;
    private javax.swing.JButton addLibrarian;
    private javax.swing.JButton viewLibrarians;
    // End of variables declaration//GEN-END:variables
}
